name: Exports secrets as environment variables
description: Exports secrets as environment variables
inputs:
  secrets:
    description: "secrets context"
    required: true
runs:
  using: composite
  steps:
    - run: |
        echo '::warning::This action was deprecated. Please use suzuki-shunsuke/tfaction/js action.'
      shell: bash
    - uses: suzuki-shunsuke/tfaction/js@18bc483f26aec8f6303f82673206b6a3d2308b7a
      id: main
      with:
        action: export-secrets
        secrets: ${{inputs.secrets}}
