name: Exports secrets as environment variables
description: Exports secrets as environment variables
inputs:
  secrets:
    description: "secrets context"
    required: true
runs:
  using: composite
  steps:
    - run: |
        echo '::warning::This action was deprecated. Please use suzuki-shunsuke/tfaction/js action.'
      shell: bash
    - uses: suzuki-shunsuke/tfaction/js@74b8864f045636196e3e1eceabbf63e510b787af
      id: main
      with:
        action: export-secrets
        secrets: ${{inputs.secrets}}
