name: List Working Directories
description: List Working Directories
outputs:
  file:
    description: Output file path
    value: ${{ steps.main.outputs.file }}
  module_file:
    description: Module file path
    value: ${{ steps.main.outputs.module_file }}
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/js@ea382a763cdf106b97c89aa5bef1c7030db5a951
      id: main
      with:
        action: list-working-dirs
