name: List Working Directories
description: List Working Directories
outputs:
  file:
    description: Output file path
    value: ${{ steps.main.outputs.file }}
  module_file:
    description: Module file path
    value: ${{ steps.main.outputs.module_file }}
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/js@2d75ac9f8fd3fd0e294d5a9e9736366472a4533b
      id: main
      with:
        action: list-working-dirs
