name: List Working Directories
description: List Working Directories
outputs:
  file:
    description: Output file path
    value: ${{ steps.main.outputs.file }}
  module_file:
    description: Module file path
    value: ${{ steps.main.outputs.module_file }}
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/js@5cb48125faa19ffb335de002aca3a9a96f4df9a7
      id: main
      with:
        action: list-working-dirs
