name: Create a pull request to scaffold a Terraform Module
description: Create a pull request to scaffold a Terraform Module
inputs:
  github_token:
    description: |
      GitHub Access Token
      contents:write - Create branches
      If skip_create_pr is false
      pull-requests:write - Create pull requests
    required: true

  securefix_action_app_id:
    description: |
      GitHub App ID for Securefix Action
      issues:write
    required: false
  securefix_action_app_private_key:
    description: |
      GitHub App Private Key for Securefix Action
    required: false
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction@68aa4ce966dcd34211b27d2d69a26c844242f712
      with:
        action: create-scaffold-module-pr
        github_token: ${{ inputs.github_token }}
        securefix_action_app_id: ${{ inputs.securefix_action_app_id }}
        securefix_action_app_private_key: ${{ inputs.securefix_action_app_private_key }}
