name: Scaffold a working directory
description: Scaffold a working directory
inputs:
  github_token:
    description: |
      GitHub Token
      No permission is necessary.
    required: false
    default: ${{ github.token }}
outputs:
  working_directory:
    description: Working Directory
    value: ${{steps.scaffold-working-dir.outputs.working_directory}}

runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction@0d079d127c296b7a61c47ca3304c03c959889b51
      with:
        action: install
    - uses: suzuki-shunsuke/tfaction@0d079d127c296b7a61c47ca3304c03c959889b51
      id: scaffold-working-dir
      with:
        action: scaffold-working-dir
      env:
        TFACTION_JOB_TYPE: scaffold_working_dir
