name: Scaffold a working directory
description: Scaffold a working directory
inputs:
  github_token:
    description: |
      GitHub Token
      No permission is necessary.
    required: false
    default: ${{ github.token }}
outputs:
  working_directory:
    description: Working Directory
    value: ${{steps.scaffold-working-dir.outputs.working_directory}}

runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction@be0dc13cdb3f9b9cc24c6cca4efa1f0a5ba3db19
      with:
        action: install
    - uses: suzuki-shunsuke/tfaction@be0dc13cdb3f9b9cc24c6cca4efa1f0a5ba3db19
      id: scaffold-working-dir
      with:
        action: scaffold-working-dir
      env:
        TFACTION_JOB_TYPE: scaffold_working_dir
