name: Release Terraform Module
description: Release Terraform Module
inputs:
  module_path:
    description: "Module path"
    required: true
  version:
    description: "module version"
    required: true
  github_token:
    description: |
      GitHub Access Token
      contents:write - Create tags and releases
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction@dd0ec4f1ca405591bf37f7d1943b62036c57eb24
      with:
        action: release-module
        module_path: ${{inputs.module_path}}
        version: ${{inputs.version}}
        github_token: ${{inputs.github_token}}
