name: Release Terraform Module
description: Release Terraform Module
inputs:
  module_path:
    description: "Module path"
    required: true
  version:
    description: "module version"
    required: true
  github_token:
    description: |
      GitHub Access Token
      contents:write - Create tags and releases
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction@fcf6d6a323f9faca7d342473f08ab9f2e7ed455b
      with:
        action: release-module
        module_path: ${{inputs.module_path}}
        version: ${{inputs.version}}
        github_token: ${{inputs.github_token}}
