name: apply
description: apply
inputs:
  github_token:
    # If `TFACTION_JOB_TYPE` is `terraform`, the following permissions are required:
    # pull-requests:write - Create pull request comments and labels
    # actions:read - Download artifacts
    # contents:write - Update pull request branches
    #
    # If `TFACTION_JOB_TYPE` is `tfmigrate`, the following permissions are required:
    # pull-requests:write - Create pull request comments
    # contents:write - Update pull request branches
    description: "GitHub Access Token"
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/terraform-apply@c6f70d0d23cc55b99c00ab6407f5ad31c1dfa452
      if: env.TFACTION_JOB_TYPE == 'terraform'
      with:
        # pull-requests:write - Create pull request comments and labels
        # actions:read - Download artifacts
        # contents:write - Update pull request branches
        github_token: ${{inputs.github_token}}

    - uses: suzuki-shunsuke/tfaction/tfmigrate-apply@c6f70d0d23cc55b99c00ab6407f5ad31c1dfa452
      if: env.TFACTION_JOB_TYPE == 'tfmigrate'
      with:
        # pull-requests:write - Create pull request comments
        # contents:write - Update pull request branches
        github_token: ${{inputs.github_token}}
