import * as exec from "@actions/exec";
import * as github from "@actions/github";
import * as path from "path";
import * as fs from "fs";
import * as tmp from "tmp";
import * as commit from "../commit";
import * as lib from "../lib";
import * as env from "../lib/env";
import * as aqua from "../aqua";

type Inputs = {
  workingDirectory: string;
  githubToken: string;
  securefixActionAppId: string;
  securefixActionAppPrivateKey: string;
  securefixActionServerRepository: string;
  executor: aqua.Executor;
};

const findConfigFile = (
  workingDirectory: string,
  repositoryRoot: string,
): string => {
  const configFiles = [
    ".terraform-docs.yml",
    ".terraform-docs.yaml",
    ".config/.terraform-docs.yml",
    ".config/.terraform-docs.yaml",
  ];

  // Search in working directory first
  for (const file of configFiles) {
    const configPath = path.join(workingDirectory, file);
    if (fs.existsSync(configPath)) {
      return file;
    }
  }

  // If not found, search in repository root
  for (const file of configFiles) {
    const configPath = path.join(repositoryRoot, file);
    if (fs.existsSync(configPath)) {
      return configPath;
    }
  }

  return "";
};

export const run = async (inputs: Inputs): Promise<void> => {
  const pwd = lib.getGitHubWorkspace();
  const readmePath = path.join(inputs.workingDirectory, "README.md");
  const executor = inputs.executor;

  // Check if README.md exists
  const created = !fs.existsSync(readmePath);

  // Create temporary file
  const tempFile = tmp.fileSync();
  try {
    // Check terraform-docs version
    await executor.exec("terraform-docs", ["-v"], {
      cwd: inputs.workingDirectory,
    });

    // Search for config file
    const config = findConfigFile(inputs.workingDirectory, pwd);

    // Build terraform-docs arguments
    const opts = config ? ["-c", config] : ["markdown"];

    const args = ["exec"];
    if (env.tfactionTarget) {
      args.push("-var", `tfaction_target:${env.tfactionTarget}`);
    }
    args.push("--", "terraform-docs", ...opts, ".");

    // Execute terraform-docs via github-comment
    const result = await executor.getExecOutput("github-comment", args, {
      cwd: inputs.workingDirectory,
      ignoreReturnCode: true,
      env: {
        GITHUB_TOKEN: inputs.githubToken,
        GH_COMMENT_CONFIG: lib.GitHubCommentConfig,
      },
    });

    // Write output to temp file
    fs.writeFileSync(tempFile.name, result.stdout);

    // Check if command failed
    if (result.exitCode !== 0) {
      throw new Error(
        `terraform-docs failed with exit code ${result.exitCode}`,
      );
    }

    // Check for error: .terraform-docs.yml is required
    const output = fs.readFileSync(tempFile.name, "utf8");
    if (output.includes("Available Commands:")) {
      throw new Error(".terraform-docs.yml is required");
    }

    // Check if README.md has the BEGIN_TF_DOCS marker
    // If not, write the entire output to README.md
    if (
      !fs.existsSync(readmePath) ||
      !fs.readFileSync(readmePath, "utf8").includes("<!-- BEGIN_TF_DOCS -->")
    ) {
      fs.writeFileSync(readmePath, output);
    }

    // Check if README.md has changed
    const diffResult = await exec.getExecOutput(
      "git",
      ["diff", "--quiet", "README.md"],
      {
        cwd: inputs.workingDirectory,
        ignoreReturnCode: true,
      },
    );

    const changed = created || diffResult.exitCode !== 0;

    if (changed) {
      const eventName = github.context.eventName;
      if (eventName !== "pull_request" && eventName !== "pull_request_target") {
        throw new Error(
          "Please generate Module's README.md with terraform-docs.",
        );
      }
      await commit.create({
        githubToken: inputs.githubToken,
        commitMessage: "docs: generate document by terraform-docs",
        appId: inputs.securefixActionAppId,
        appPrivateKey: inputs.securefixActionAppPrivateKey,
        serverRepository: inputs.securefixActionServerRepository,
        files: new Set([path.join(inputs.workingDirectory, "README.md")]),
      });
      throw new Error("document is generated by terraform-docs");
    }
  } finally {
    // Clean up temporary file
    tempFile.removeCallback();
  }
};
