name: Exports AWS Secrets Manager's secrets as environment variables
description: Exports AWS Secrets Manager's secrets as environment variables
runs:
  using: composite
  steps:
    - run: |
        echo '::warning::This action was deprecated. Please use suzuki-shunsuke/tfaction/js action.'
      shell: bash
    - uses: suzuki-shunsuke/tfaction/js@f233fdc7c528d1d417cd88541384e6c69f491892
      id: main
      with:
        action: export-aws-secrets-manager
