name: Exports AWS Secrets Manager's secrets as environment variables
description: Exports AWS Secrets Manager's secrets as environment variables
runs:
  using: composite
  steps:
    - run: |
        echo '::warning::This action was deprecated. Please use suzuki-shunsuke/tfaction/js action.'
      shell: bash
    - uses: suzuki-shunsuke/tfaction/js@bd38a1f2332f5e1366086d7255daa1ef2606d593
      id: main
      with:
        action: export-aws-secrets-manager
