name: Exports AWS Secrets Manager's secrets as environment variables
description: Exports AWS Secrets Manager's secrets as environment variables
runs:
  using: composite
  steps:
    - run: |
        echo '::warning::This action was deprecated. Please use suzuki-shunsuke/tfaction/js action.'
      shell: bash
    - uses: suzuki-shunsuke/tfaction/js@7b56a9e2307c1aeaf406dafa7a221189a1bdd3f6
      id: main
      with:
        action: export-aws-secrets-manager
