name: Update the latest branch
on:
  push:
    branches:
      - main
jobs:
  release:
    uses: ./.github/workflows/wc-release.yaml
    with:
      version: latest
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}
    permissions:
      contents: write
      pull-requests: write
      id-token: write
