---
name: Generate document from JSON Schema and deploy
on: workflow_call

jobs:
  deploy-schema:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.60.1
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: pip install json-schema-for-humans
      - run: cmdx schema
      - run: cmdx schema-doc

      - uses: suzuki-shunsuke/gh-pages-action@ce95bfca768d3d1a0454f8efb6f81a557a18bc68 # v0.1.0
        if: github.event_name != 'pull_request'
        with:
          publish_dir: build
          destination_dir: config
