---
name: wc-release
run-name: wc-release (${{inputs.pr}})
on:
  workflow_call:
    inputs:
      version:
        description: "Version"
        required: true
        type: string
      pr:
        description: "Pull Request Number"
        required: false
        type: string
      is_comment:
        description: If the comment is posted
        required: false
        default: false
        type: boolean
    secrets:
      TAKUMI_GUARD_BOT_ID:
        required: true

jobs:
  release:
    timeout-minutes: 15
    runs-on: ubuntu-26.04
    permissions:
      contents: write
      pull-requests: write
      id-token: write # Required for OIDC
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: gh pr checkout "$PR"
        if: inputs.pr != ''
        env:
          GITHUB_TOKEN: ${{github.token}}
          PR: ${{inputs.pr}}

      - uses: aquaproj/aqua-installer@82d0e83878a8657c4a6f2ff1755d3bfbfc67f329 # v4.1.0
        with:
          aqua_version: v2.64.0
        env:
          GITHUB_TOKEN: ${{github.token}}

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          cache: npm
      - uses: flatt-security/setup-takumi-guard-npm@14f07d0cbc739b42a1b7c70a04c2b84cd1318ddd # v1.4.0
        with:
          bot-id: ${{secrets.TAKUMI_GUARD_BOT_ID}}
      - run: npm ci

      - run: cmdx -v
        env:
          GITHUB_TOKEN: ${{github.token}}

      - run: cmdx build

      - uses: suzuki-shunsuke/release-js-action@ff106e3a3f5b34f174a23db3110031fbf463f15c # v0.2.1
        with:
          version: ${{inputs.version}}
          is_comment: ${{inputs.is_comment}}
          files: |
            schema/tfaction.json
            schema/tfaction-root.json

      - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          path: dist
          name: js
