---
name: wc-test
on:
  workflow_call:
    secrets:
      TAKUMI_GUARD_BOT_ID:
        required: true
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-26.04
    permissions:
      id-token: write # Required for OIDC
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: flatt-security/setup-takumi-guard-npm@14f07d0cbc739b42a1b7c70a04c2b84cd1318ddd # v1.4.0
        with:
          bot-id: ${{secrets.TAKUMI_GUARD_BOT_ID}}
      - run: npm ci
      - run: npm t
      - run: npx eslint
