name: test (workflow_call)
on:
  workflow_call:
    secrets:
      gh_app_id:
        required: false
      gh_app_private_key:
        required: false
      TAKUMI_GUARD_BOT_ID:
        required: true
jobs:
  path-filter:
    # Get changed files to filter jobs
    timeout-minutes: 10
    outputs:
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
      ghalint: ${{steps.changes.outputs.ghalint}}
    runs-on: ubuntu-26.04
    permissions: {}
    steps:
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: changes
        with:
          filters: |
            build-schema:
              - .github/workflows/test.yaml
              - .github/workflows/wc-deploy-schema.yaml
              - "schema/**"

  test:
    uses: suzuki-shunsuke/test-workflow/.github/workflows/test.yaml@51ece8dcaabff59820bfb2053c56e3cb281cf7b2 # v0.0.1
    with:
      aqua_version: v2.64.0
    permissions:
      pull-requests: read
      contents: read

  build-schema:
    uses: ./.github/workflows/wc-deploy-schema.yaml
    permissions:
      contents: write

  js:
    uses: ./.github/workflows/wc-test.yaml
    permissions:
      id-token: write
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}

  create-pr-branch:
    uses: ./.github/workflows/wc-create-pr-branch.yaml
    if: |
      ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    with:
      pr: ${{github.event.pull_request.number}}
    secrets:
      gh_app_id: ${{secrets.gh_app_id}}
      gh_app_private_key: ${{secrets.gh_app_private_key}}
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}

  test_deploy_doc:
    uses: ./.github/workflows/workflow_call_deploy_doc.yaml
    permissions:
      issues: write
      contents: write
